# Generated by Django 3.1.7 on 2021-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name', 'location']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['customer', 'host']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(help_text='Enter e.g. Microsoft Deutschland GmBH, Meitnerstraße 9, 70563 Stuttgart', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='suffix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
