# Generated by Django 3.1.7 on 2021-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_auto_20210324_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(help_text='e.g. Meitnerstraße 9, 70563 Stuttgart', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(help_text='e.g. Stuttgart', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='e.g. Microsoft Deutschland GmbH', max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='host',
            field=models.CharField(help_text='e.g. 127.0.0.1', max_length=150),
        ),
        migrations.AlterField(
            model_name='system',
            name='password',
            field=models.CharField(help_text='password to access system', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='port',
            field=models.CharField(default='443', help_text='e.g. 443', max_length=5),
        ),
        migrations.AlterField(
            model_name='system',
            name='suffix',
            field=models.CharField(help_text='e.g. 127.0.0.1', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='token',
            field=models.CharField(help_text='OATH Token to access system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='user',
            field=models.CharField(help_text='username to access system', max_length=20, null=True),
        ),
    ]
