# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_auto_20210324_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='protocol',
            field=models.CharField(default='https', help_text='e.g. https', max_length=5),
        ),
    ]
