# Generated by Django 3.1.7 on 2021-03-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0006_auto_20210324_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='password',
            field=models.CharField(help_text='password to access system', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='token',
            field=models.CharField(help_text='OATH Token to access system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='user',
            field=models.CharField(help_text='username to access system', max_length=20, null=True),
        ),
    ]
