# Generated by Django 3.1.7 on 2021-03-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0007_auto_20210324_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', help_text='e.g. Meitnerstraße 9, 70563 Stuttgart', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, default='', help_text='e.g. Stuttgart', max_length=70),
        ),
        migrations.AlterField(
            model_name='system',
            name='password',
            field=models.CharField(blank=True, default='', help_text='password to access system', max_length=30),
        ),
        migrations.AlterField(
            model_name='system',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text='e.g. 127.0.0.1', max_length=200),
        ),
        migrations.AlterField(
            model_name='system',
            name='token',
            field=models.CharField(blank=True, default='', help_text='OATH Token to access system', max_length=255),
        ),
        migrations.AlterField(
            model_name='system',
            name='user',
            field=models.CharField(blank=True, default='', help_text='username to access system', max_length=20),
        ),
    ]
