# Generated by Django 3.1.7 on 2021-03-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_auto_20210324_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name', 'location'], 'permissions': (('can_see_all_customers', 'Can See all customers'),)},
        ),
    ]
