# Generated by Django 3.1.7 on 2021-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0009_auto_20210327_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name', 'location'], 'permissions': (('can_see_all_customers', 'Can see all customers'),)},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['customer', 'host'], 'permissions': (('can_see_all_systems', 'Can see all systems'),)},
        ),
    ]
